version: '3.9'

services:
  text_generation_app:
    image: ${TEAM_MEMBER_NAME_LOWER}_image
    container_name: ${TEAM_MEMBER_NAME_LOWER}_container
    build:
      context: .
      args:
        - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8080:8080"
    environment:
      - MODEL_PATH=/app/model