# Define Phony targets
.Phony: help download-model

# Download model from Hugging Face
download-model:
	@echo "Downloading model..."
	python ./download_model.py

# Show help message
help:
	@echo "	Available commands:"
	@echo "	- download-model: Download model from Hugging Face"
	@echo "	- help: Show this help message"
